fix: test2

diff --git a/.github/workflows/publish_to_dev_to.yaml b/.github/workflows/publish_to_dev_to.yaml
--- a/.github/workflows/publish_to_dev_to.yaml
+++ b/.github/workflows/publish_to_dev_to.yaml
@@ -16,6 +16,7 @@ jobs:
 
     - name: Find latest article by commit date
       run: |
+        cd $GITHUB_WORKSPACE
         latest_article=$(git log -1 --pretty=format: --name-only -- content/blogs/**/*.md | grep -v 'content/blogs/_index.md' | head -n 1)
         if [ -z "$latest_article" ]; then
           echo "No article found"
@@ -25,6 +26,7 @@ jobs:
 
     - name: Replace relative paths with GitHub raw content URLs
       run: |
+        cd $GITHUB_WORKSPACE
         repo_url="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/"
         latest_article_dir=$(dirname "$latest_article")
 
@@ -33,8 +35,8 @@ jobs:
         echo "Latest article directory: $latest_article_dir"
 
         # Ensure the directory path is correct
-        if [ -z "$latest_article_dir" ]; then
-          latest_article_dir="."
+        if [ -z "$latest_article_dir" ] || [ "$latest_article_dir" = "." ]; then
+          latest_article_dir=$(dirname "$latest_article")
         fi
 
         # Update the sed command to remove ./ while replacing
@@ -80,7 +82,12 @@ jobs:
         if [ $? -eq 0 ]; then
           article_id=$(echo $response | jq -r '.id')
           echo "id: $article_id" | cat - latest_article.md > temp && mv temp latest_article.md
-          echo "id: $article_id" | cat - latest_article.md > temp && mv temp "$latest_article"
+          if [ ! -d "$latest_article" ]; then
+            echo "id: $article_id" | cat - latest_article.md > temp && mv temp "$latest_article"
+          else
+            echo "Cannot overwrite directory with non-directory"
+            exit 1
+          fi
         else
           echo "Failed to publish article to dev.to"
           exit 1
