fix: test

diff --git a/.github/workflows/publish_to_dev_to.yaml b/.github/workflows/publish_to_dev_to.yaml
--- a/.github/workflows/publish_to_dev_to.yaml
+++ b/.github/workflows/publish_to_dev_to.yaml
@@ -25,8 +25,9 @@ jobs:
 
     - name: Replace relative paths with GitHub raw content URLs
       run: |
-        repo_url="https://raw.githubusercontent.com/${{ github.repository }}/main/"
-        sed -i "s|!\[\([^]]*\)\](\(\./[^)]*\))|![\1]($repo_url\2)|g" latest_article.md
+        repo_url="https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main"
+        latest_article_dir=$(dirname "$latest_article")
+        sed -i "s|!\[\([^]]*\)\](\(\./[^)]*\))|![\1]($repo_url$latest_article_dir/\2)|g" latest_article.md
 
     - name: Extract title from article
       run: |
@@ -61,9 +62,14 @@ jobs:
           -H "Content-Type: application/json" \
           -H "api-key: $DEVTO_API_KEY" \
           -d "$request_body" https://dev.to/api/articles)
-        article_id=$(echo $response | jq -r '.id')
-        echo "id: $article_id" | cat - latest_article.md > temp && mv temp latest_article.md
-        echo "id: $article_id" | cat - $latest_article > temp && mv temp $latest_article
+        if [ $? -eq 0 ]; then
+          article_id=$(echo $response | jq -r '.id')
+          echo "id: $article_id" | cat - latest_article.md > temp && mv temp latest_article.md
+          echo "id: $article_id" | cat - latest_article.md > temp && mv temp "$latest_article"
+        else
+          echo "Failed to publish article to dev.to"
+          exit 1
+        fi
 
     - name: Commit changes
       run: |
